name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  deploy:
    name: Build and deploy to production
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - run: deno task build
    - name: rsync
      run: |
        echo "${{ secrets.YOZO_OOO_SSH_PRIVATE_KEY }}" > deploy_key
        chmod 600 ./deploy_key
        rsync \
          --archive \
          --delete \
          --exclude=.htaccess \
          --rsh='ssh -i ./deploy_key -o StrictHostKeyChecking=no -o LogLevel=quiet' \
          dist/ ${{ secrets.YOZO_OOO_REMOTE }}:/var/www/yozo.ooo
